### PR TITLE
Convert DependencyGraph from groovy to java

### PR DESCRIPTION
**Pull request by lhotari**
The Spring DM plugin causes a performance bottleneck in large enterprise builds. Profiling with Java Flight Recorder shows that one of the hotspots is in the DependencyGraphNode.collectById method. This PR simply converts the Groovy code to Java code to make this hotspot execute faster without the overhead of dynamic Groovy code execution.
I started the conversion with IntelliJ's "Convert to Java" refactoring and removed the use of DefaultGroovyMethods and Groovy Closures manually. The goal was to make 1-to-1 conversion from Groovy to Java without changing behaviour.
Another alternative would be to convert dynamic Groovy code to use CompileStatic. That would perhaps change the minimum version to Gradle 2.8 since that's the first version of Gradle with Groovy 2.4.x (2.4.4). Even with CompileStatic, it helps performance to replace "each + closure" iteration with normal for loops.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks, @lhotari. Can you please [sign the CLA](https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/master/CONTRIBUTING.md#sign-the-contributor-license-agreement)?

I don't want to drop support for Gradle 1.x just yet, so a Java conversion feels like the best solution.

Do you have a "large enterprise build" that you could share? I'm interested to see if there's anywhere else that's an obvious bottleneck.

**Comment by lhotari** [comment]
This reproduces the performance problem. This example has JFR profiler enabled: ```
git clone -b lh-spring-dm-perf-test --depth 1 https://github.com/lhotari/gradle
cd gradle
./gradlew -PspringDmPluginVersion=0.5.6.RELEASE -PmaxProjects=20 lotProjectDependencies
cd subprojects/performance/build/lotProjectDependencies
GRADLE_OPTS="-Xmx4g -XX:+UnlockCommercialFeatures -XX:+FlightRecorder -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -XX:FlightRecorderOptions=defaultrecording=true,settings=profile,disk=true,maxsize=500M,stackdepth=1024,dumponexit=true" gradle --no-search-upward --no-daemon resolveDependencies
jmc -open hotspot-pid-*.jfr
```
I'd using sdkman and gradle points to Gradle version 2.13 .
For me, It really starts crawling after project11 .

**Comment by lhotari** [comment]
I have signed the CLA.

**Comment by lhotari** [comment]
The build failed for me at project17 with "GC overhead limit exceeded".

**Comment by lhotari** [comment]
with `-PmaxProjects=14`, it passes.

**Comment by lhotari** [comment]
With `-PmaxProject=14`, the `0.5.6.RELEASE` version takes 46 seconds. with this change , it takes 20 seconds.

**Comment by lhotari** [comment]
[Flamegraph with this change](https://gist.github.com/lhotari/57f9dfd71647c8d069824580c9f9d4ee)
[Flamegraph 0.5.6.RELEASE](https://gist.github.com/lhotari/b0871e8189b60dd67b40fe9855bed01f)
created with [jfr-report-tool](https://github.com/lhotari/jfr-report-tool)

**Comment by wilkinsona** [comment]
@lhotari Thank you very much, this is hugely helpful.

I have another issue (#79) that reported the "GC overhead limit exceeded" problem but I had been unable to reproduce it. Your performance test gives me what I need and shows that the graph needs to be stored more efficiently. Thanks again.

**Comment by lhotari** [comment]
@wilkinsona Thanks for polishing and merging this.

**Pull request closed without merging**
