### PR TITLE
Pom classifier support

### PR DESCRIPTION
**Pull request by fpape**
adds classifier to generated pom as described in https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/67.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Thanks for the PR. Like other Spring projects, this project's covered by our [contributor licence agreement](https://support.springsource.com/spring_committer_signup) but the signup page doesn't list this project yet. This is the first non-trivial PR that's been submitted so I now need to get that set up properly. That might take a few days so please bear with me.

**Comment by fpape** [comment]
Hi Andy,

I've noticed the 'Dependency Management Gradle Plugin' is now listed in 
the projects dropdown.

I'm not sure what to enter in the 'Project Lead' field.

Thanks,

Frederic

**Comment by wilkinsona** [comment]
@fpape Excellent. That was quicker than I thought it would be. Please use "Andy Wilkinson" in the project lead field.

**Comment by RealNitro** [comment]
I accepted the license agreement. (Contributed  the tests.)

**Comment by fpape** [comment]
Andy,

I accepted the license.

With kind regards,
Frederic

**Comment by wilkinsona** [comment]
@fpape Thanks for your efforts, but, for the reasons stated in [this comment](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/67#issuecomment-179248638), I don't think it's a good idea to accept these changes.

**Pull request closed without merging**
