### PR TITLE
Improve DSL to add properties to the generated BOM

### PR DESCRIPTION
**Pull request by jlafourc**
Hi,
I implemented a small new feature in the existing DSL to add properties when the bom is generated. 

Example : 

```
<properties>
  <springboot.version>1.4.2.RELEASE</springboot.version>
  <spring.version>4.1.1.RELEASE</spring.version>
</properties>
```

Julien

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jlafourc Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-gradle-plugins/dependency-management-plugin&pullRequestId=142)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-gradle-plugins/dependency-management-plugin&pullRequestId=142) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jlafourc Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-gradle-plugins/dependency-management-plugin&pullRequestId=142)!

**Comment by wilkinsona** [comment]
Interesting. Thanks for the PR.

There's some overlap here with what https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/master/src/main/java/io/spring/gradle/dependencymanagement/dsl/MavenBomHandler.java provides. I think we'll need to address that overlap before merging this, but I'm not 100% sure of the best way to do so. MavenBomHandler applies properties per import which you can't do in a POM…

**Comment by jlafourc** [comment]
I checked that part before implementing the feature. But from what I understood, the MavenBomHandler provides DSL to specify propety values tu use while importing the BOM. 

My PR is the other way: specify properties when generating a BOM.

**Comment by wilkinsona** [comment]
Right. There's still some conceptual overlap there in my opinion. Also, without tying the two together there's no major benefit  to what you've proposed over using Gradle's standard API for customising a generated pom.

**Comment by wilkinsona** [comment]
Another consideration is that properties in a pom only override properties from inherited poms and not those in imported poms. This plugin only imports poms in the generated pom rather than setting one as the parent so setting properties in the generated pom will be of limited or even no benefit.

**Comment by jlafourc** [comment]
Thanks for taking to time answer.

> Also, without tying the two together there's no major benefit to what you've proposed over using Gradle's standard API for customising a generated pom.

That's true. It could be done a separate plugin. I just think that for properties defining versions of dependencies, it is convinient to declare them close. 

At my company, we have a lot of projects and we'd like to centralize versions of external dependencies in boms (at the moment we apply a separate gradle file which declares the versions, but it is slow and less customizable than boms). The DSL seems perfect to generate those boms except we miss properties. 

Properties look great if a particular team wants to bump a version locally in one of their project. The plugin provides that functionnality with `bomProperty` when the bom is imported.

So two kinds of projects using the plugin in two different ways.

**Comment by wilkinsona** [comment]
> The DSL seems perfect to generate those boms except we miss properties.

As I said above, properties are of no use in a bom if that bom's going to be imported in a pom.xml (Maven only supports overriding a parent pom's properties). Providing a detailed DSL for pom generation is also outside of this plugin's area of focus. Thanks for the suggestion but for these reasons I'm going to close this PR.

**Comment by jlafourc** [comment]
Hi,

I'll just try one last time with a gist : 

https://gist.github.com/jlafourc/379da4500d205ca88e151c3803f06ade

This generate-bom.gradle generates a BOM I think. Then consume-bom.gradle imports that BOM. I just wanted to improve the DSL to specify properties in the generated BOM (like in generate-bom-with-properties.gradle). 

Thanks for everything. 

Julien

**Pull request closed without merging**
