### PR TITLE
Notreplver

### PR DESCRIPTION
**Pull request by marvertin**
Not replace explicitly defined versions in dependencies.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@marvertin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-gradle-plugins/dependency-management-plugin&pullRequestId=253)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-gradle-plugins/dependency-management-plugin&pullRequestId=253) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@marvertin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-gradle-plugins/dependency-management-plugin&pullRequestId=253)!

**Comment by wilkinsona** [comment]
Thanks for the pull request. Can you please describe the problem that the proposed changes are trying to solve? It looks like you want the dependency management to honour the version that's provided on a dependency declaration. It should already do this as shown by [this test](https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/e2d3affdd01918d95ef6b30565fbd0f54a9938c6/src/test/groovy/io/spring/gradle/dependencymanagement/DependencyManagementPluginSpec.groovy#L193-L211).

**Comment by marvertin** [comment]
I am sorry, there is bad code in the pull request.

**Pull request closed without merging**
