### PR TITLE
Notreplver

### PR DESCRIPTION
**Pull request by marvertin**
Replace module version ONLY if version was not specified.

### CODE REVIEW

**Comment by wilkinsona** [comment]
Just for further reference, rather than closing #253 you could have pushed additional changes to your branch and updated it. We're here now though so let's stick with this new pull request where I have the same question as before:

> Can you please describe the problem that the proposed changes are trying to solve? It looks like you want the dependency management to honour the version that's provided on a dependency declaration. It should already do this as shown by this test.

**Comment by wilkinsona** [comment]
Closing due to the lack of the requested feedback. We can re-open this pull request if the feedback is provided in the future.

**Comment by marvertin** [comment]
For example tin this build:

    plugins {
        id 'org.springframework.boot' version '2.1.2.RELEASE'
        id 'java'
    }

    apply plugin: 'io.spring.dependency-management'

    repositories { 
        mavenCentral()
    }

    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-actuator'
        implementation 'org.springframework.boot:spring-boot-starter-amqp:2.1.6.RELEASE'
    }

spring-rabbit version is downgraded from 2.1.7 to 2.1.3, because acturator has optional dependency on strping-rabit 2.1.3. My version of the plugin solve this problem, beacause it only sets version if no version was computed by any mechanism.

    gradlew dI --dependency spring-rabbit

gives this output

     >Task :dependencyInsight
     org.springframework.amqp:spring-rabbit:2.1.3.RELEASE (selected by rule)
       variant "compile" [
          org.gradle.status              = release (not requested)
          org.gradle.usage               = java-api
          org.gradle.category            = library (not requested)

          Requested attributes not found in the selected variant:
             org.gradle.dependency.bundling = external
             org.gradle.jvm.version         = 8
       ]

    org.springframework.amqp:spring-rabbit:2.1.7.RELEASE -> 2.1.3.RELEASE
    \--- org.springframework.boot:spring-boot-starter-amqp:2.1.6.RELEASE
         \--- compileClasspath`

**Comment by wilkinsona** [comment]
That sounds like useful functionality, but it is out of the scope of this plugin which is intended to provide Maven-like dependency management.

In your example above, the `spring-boot-dependencies` bom from Spring Boot 2.1.2 will have been imported. This bom [manages the version of Spring AMQP](https://github.com/spring-projects/spring-boot/blob/aa3bfff9f2603c70882f863b3a61d83dfdb47e4c/spring-boot-project/spring-boot-dependencies/pom.xml#L166). The plugin is honouring the import of the bom and setting the version of the `spring-rabbit` module accordingly.

**Pull request closed without merging**
